const ERROR_LOGIN_PASSWORD_INVALID = 'ERROR_LOGIN_PASSWORD_INVALID';
const ERROR_USER_NOT_VERIFICATION = 'ERROR_USER_NOT_VERIFICATION';
const ERROR_EMAIL_TAKEN = 'ERROR_EMAIL_TAKEN';
const ERROR_LOGIN_TAKEN = 'ERROR_LOGIN_TAKEN';
const ERROR_NO_USER = 'ERROR_NO_USER';
const ERROR_TOKEN_INVALID = 'ERROR_TOKEN_INVALID';
const ERROR_OLD_PASSWORD_INVALID = 'ERROR_OLD_PASSWORD_INVALID';
const INVALID_PASSWORD_RECOVERY_LINK = 'INVALID_PASSWORD_RECOVERY_LINK';

export {
    ERROR_LOGIN_PASSWORD_INVALID,
    ERROR_USER_NOT_VERIFICATION,
    ERROR_EMAIL_TAKEN,
    ERROR_LOGIN_TAKEN,
    ERROR_NO_USER,
    ERROR_TOKEN_INVALID,
    ERROR_OLD_PASSWORD_INVALID,
    INVALID_PASSWORD_RECOVERY_LINK,
};
